# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - id: mac
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      amd64: x86_64
checksum:
  name_template: 'checksums-mac.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: waldkauz

    # GitHub/GitLab repository to push the formula to
    tap:
      owner: michherren
      name: homebrew-waldkauz

      # Optionally a token can be provided, if it differs from the token provided to GoReleaser
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    # Caveats for the user of your binary.
    # Default is empty.
    caveats: "Start the binary and follow the install instructions"

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/michherren/waldkauz"

    # Template of your app's description.
    # Default is empty.
    description: "Redpanda Console Kafka client as a single static binary."

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "MIT"

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    #install: |
    #  bin.install "program"